---
title: تاریخ عقاید اقتصادی
timezone: Asia/Tehran

collections:
  steps:
    title: Steps
    output: false
    order:
      - xenophon.md
      - verdi.md
      - tchaikovsky.md
      - mozart.md
      - beethoven.md
      - chopin.md
      - bach.md

#defaults:
#- scope:
#    path: ''
#    type: steps
#  values:
#    title: 
#    date: 2020-01-01 00:00:00 -0700

markdown: kramdown
highlighter: rouge
lsi: false
description: 
baseurl:
url: 
color: "#f2f2f2"

plugins:
        - jekyll-paginate-v2

exclude:
        - Gemfile
        - Gemfile.lock

pagination:
  enabled: true
  collection: 'steps'
  per_page: 10 
  permalink: '/:num/'
  sort_field: 'order'
